#!/usr/bin/python3
import argparse
import os

def subdir_exist():
    content = None
    fname = "subdir"
    if os.path.isfile(fname):
        with open(fname) as f:
            content = f.readlines()
    return content

def main():
    print("Welcome to autodeb")

    parser = argparse.ArgumentParser()
    parser.add_argument('-s','--src_url', action='store',
            dest='src_url',
            help='URL where the code is stored')

    results = parser.parse_args()
    if results.src_url:
        print(results.src_url)
        subdir = subdir_exist()
        if subdir:
            print(subdir)

if __name__ == '__main__':
    main()
